[theme]

primaryColor = "#22C55E"              # Neon green soft
backgroundColor = "#0F172A"           # Dark navy (bukan hitam polos)
secondaryBackgroundColor = "#1E293B"  # Card lebih terang
textColor = "#E5E7EB"                 # Abu terang (nyaman)
font = "sans serif"
