[theme]

primaryColor = "#00E676"              # Neon green (hacker accent)
backgroundColor = "#0B0F14"           # Dark almost-black (premium hacker)
secondaryBackgroundColor = "#111827"  # Card / sidebar
textColor = "#D1D5DB"                 # Soft white (anti capek mata)
font = "sans serif"
